name: win-build-on-tag
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with: { lfs: true }
      - name: Build Windows IL2CPP
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          allowDirtyBuild: true
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: WindowsBuild
          path: build
